### ISSUE TITLE
API changed? "Oops! Too many time click to page"

### ISSUE THREAD

**Issue by 2600box** [kairoaraujo/python-kodaksmarthome#27]
Does this still work for anyone in EU?

Does this need to be reworked?

I get this error from the API:

```
Python 3.9.2 (default, May 30 2021, 22:58:55)
[Clang 12.0.5 (clang-1205.0.22.9)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> from kodaksmarthome import KodakSmartHome
>>> my_home = KodakSmartHome('XXX', 'XXX')
>>> my_home.connect()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/XXX/dev/python-kodaksmarthome/kodaksmarthome/api.py", line 322, in connect
    self._get_events()
  File "/Users/XXX/dev/python-kodaksmarthome/kodaksmarthome/api.py", line 287, in _get_events
    events_response = self._http_request(
  File "/Users/XXX/dev/python-kodaksmarthome/kodaksmarthome/api.py", line 157, in _http_request
    raise ConnectionError(
ConnectionError: Unexpected HTTP CODE error <!DOCTYPE html>
<html lang="en">

<head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->

        <title>503 HTML Template by Ebuynow</title>

        <!-- Google font -->
        <link href="https://fonts.googleapis.com/css?family=Cabin:400,700" rel="stylesheet">
        <link href="https://fonts.googleapis.com/css?family=Montserrat:900" rel="stylesheet">

        <!-- Custom stlylesheet -->
        <link type="text/css" rel="stylesheet" href="css/style.css" />

        <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
        <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
        <!--[if lt IE 9]>
                  <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
                  <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
                <![endif]-->

</head>

<body>

        <div id="notfound">
                <div class="notfound">
                        <div class="Warning-404">
                                <h3>Oops! Too many time click to page</h3>
                        </div>
                        <h2>we are sorry, but you must wait several seconds to access again!</h2>
                </div>
        </div>

</body><!-- This templates was made by Colorlib (https://colorlib.com) -->

</html>


>>>
```

**Comment by 2600box** [comment]
Adding a 10 second delay seems to help:

# api.py

import time  # Import the time module for sleep functionality

# ... (existing code)

self.events = list()
for device in self.devices:
    device_id = device["device_id"]
    device_events = {"device_id": device_id, "events": list()}
    pages = 1
    events_pages = 1
    while pages <= events_pages:
        url_events = (
            f"{self.region_url.URL}/user/device/event?"
            + f"deviceId={device_id}&"
            + f"page={pages}"
        )
        
        time.sleep(10)  # Add a delay of 10 seconds before making the request

        events_response = self._http_request(
            "GET", url_events, headers=headers
        )

        # ... (existing code)
